<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entities\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bio' => [parent::class, 'bio', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'deletedAt' => [parent::class, 'deletedAt', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'family' => [parent::class, 'family', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'is_private_investor' => [parent::class, 'is_private_investor', null],
        "\0".parent::class."\0".'is_sejami' => [parent::class, 'is_sejami', null],
        "\0".parent::class."\0".'mobile' => [parent::class, 'mobile', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'orders' => [parent::class, 'orders', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'status_id' => [parent::class, 'status_id', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'usersInfosValues' => [parent::class, 'usersInfosValues', null],
        'bio' => [parent::class, 'bio', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'deletedAt' => [parent::class, 'deletedAt', null],
        'email' => [parent::class, 'email', null],
        'family' => [parent::class, 'family', null],
        'id' => [parent::class, 'id', null],
        'is_private_investor' => [parent::class, 'is_private_investor', null],
        'is_sejami' => [parent::class, 'is_sejami', null],
        'mobile' => [parent::class, 'mobile', null],
        'name' => [parent::class, 'name', null],
        'orders' => [parent::class, 'orders', null],
        'password' => [parent::class, 'password', null],
        'status' => [parent::class, 'status', null],
        'status_id' => [parent::class, 'status_id', null],
        'type' => [parent::class, 'type', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'usersInfosValues' => [parent::class, 'usersInfosValues', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
