<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Project extends \App\Entities\Project implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cityId' => [parent::class, 'cityId', null],
        "\0".parent::class."\0".'companyIntro' => [parent::class, 'companyIntro', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'expertOpinion' => [parent::class, 'expertOpinion', null],
        "\0".parent::class."\0".'farabourseProject' => [parent::class, 'farabourseProject', null],
        "\0".parent::class."\0".'fundingPeriod' => [parent::class, 'fundingPeriod', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'participationGenerated' => [parent::class, 'participationGenerated', null],
        "\0".parent::class."\0".'percent' => [parent::class, 'percent', null],
        "\0".parent::class."\0".'projectIntro' => [parent::class, 'projectIntro', null],
        "\0".parent::class."\0".'projectRisks' => [parent::class, 'projectRisks', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'warranty' => [parent::class, 'warranty', null],
        "\0".parent::class."\0".'warrantyDetails' => [parent::class, 'warrantyDetails', null],
        'cityId' => [parent::class, 'cityId', null],
        'companyIntro' => [parent::class, 'companyIntro', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'expertOpinion' => [parent::class, 'expertOpinion', null],
        'farabourseProject' => [parent::class, 'farabourseProject', null],
        'fundingPeriod' => [parent::class, 'fundingPeriod', null],
        'id' => [parent::class, 'id', null],
        'participationGenerated' => [parent::class, 'participationGenerated', null],
        'percent' => [parent::class, 'percent', null],
        'projectIntro' => [parent::class, 'projectIntro', null],
        'projectRisks' => [parent::class, 'projectRisks', null],
        'slug' => [parent::class, 'slug', null],
        'status' => [parent::class, 'status', null],
        'title' => [parent::class, 'title', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'user' => [parent::class, 'user', null],
        'warranty' => [parent::class, 'warranty', null],
        'warrantyDetails' => [parent::class, 'warrantyDetails', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
