<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FarabourseProject extends \App\Entities\FarabourseProject implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'approvedUnderwritingEndDate' => [parent::class, 'approvedUnderwritingEndDate', null],
        "\0".parent::class."\0".'approvedUnderwritingStartDate' => [parent::class, 'approvedUnderwritingStartDate', null],
        "\0".parent::class."\0".'companyUnits' => [parent::class, 'companyUnits', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'crowdFundingDescription' => [parent::class, 'crowdFundingDescription', null],
        "\0".parent::class."\0".'crowdFundingId' => [parent::class, 'crowdFundingId', null],
        "\0".parent::class."\0".'englishName' => [parent::class, 'englishName', null],
        "\0".parent::class."\0".'englishSymbol' => [parent::class, 'englishSymbol', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'industryGroup' => [parent::class, 'industryGroup', null],
        "\0".parent::class."\0".'legalPersonMaximumAvailablePrice' => [parent::class, 'legalPersonMaximumAvailablePrice', null],
        "\0".parent::class."\0".'legalPersonMinimumAvailablePrice' => [parent::class, 'legalPersonMinimumAvailablePrice', null],
        "\0".parent::class."\0".'minimumRequirePrice' => [parent::class, 'minimumRequirePrice', null],
        "\0".parent::class."\0".'numberOfFinanceProvider' => [parent::class, 'numberOfFinanceProvider', null],
        "\0".parent::class."\0".'persianName' => [parent::class, 'persianName', null],
        "\0".parent::class."\0".'persianSymbol' => [parent::class, 'persianSymbol', null],
        "\0".parent::class."\0".'project' => [parent::class, 'project', null],
        "\0".parent::class."\0".'projectEndDate' => [parent::class, 'projectEndDate', null],
        "\0".parent::class."\0".'projectReportingTypeDescription' => [parent::class, 'projectReportingTypeDescription', null],
        "\0".parent::class."\0".'projectStartDate' => [parent::class, 'projectStartDate', null],
        "\0".parent::class."\0".'projectStatusDescription' => [parent::class, 'projectStatusDescription', null],
        "\0".parent::class."\0".'projectStatusId' => [parent::class, 'projectStatusId', null],
        "\0".parent::class."\0".'realPersonMaximumAvailablePrice' => [parent::class, 'realPersonMaximumAvailablePrice', null],
        "\0".parent::class."\0".'realPersonMinimumAvailablePrice' => [parent::class, 'realPersonMinimumAvailablePrice', null],
        "\0".parent::class."\0".'settlementDescription' => [parent::class, 'settlementDescription', null],
        "\0".parent::class."\0".'subIndustryGroup' => [parent::class, 'subIndustryGroup', null],
        "\0".parent::class."\0".'suggestedUnderwritingEndDate' => [parent::class, 'suggestedUnderwritingEndDate', null],
        "\0".parent::class."\0".'suggestedUnderwritingStartDate' => [parent::class, 'suggestedUnderwritingStartDate', null],
        "\0".parent::class."\0".'sumOfFoundingProvided' => [parent::class, 'sumOfFoundingProvided', null],
        "\0".parent::class."\0".'totalAmounts' => [parent::class, 'totalAmounts', null],
        "\0".parent::class."\0".'totalUnit' => [parent::class, 'totalUnit', null],
        "\0".parent::class."\0".'traceCode' => [parent::class, 'traceCode', null],
        "\0".parent::class."\0".'underwritingDuration' => [parent::class, 'underwritingDuration', null],
        "\0".parent::class."\0".'unitPrice' => [parent::class, 'unitPrice', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'approvedUnderwritingEndDate' => [parent::class, 'approvedUnderwritingEndDate', null],
        'approvedUnderwritingStartDate' => [parent::class, 'approvedUnderwritingStartDate', null],
        'companyUnits' => [parent::class, 'companyUnits', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'crowdFundingDescription' => [parent::class, 'crowdFundingDescription', null],
        'crowdFundingId' => [parent::class, 'crowdFundingId', null],
        'englishName' => [parent::class, 'englishName', null],
        'englishSymbol' => [parent::class, 'englishSymbol', null],
        'id' => [parent::class, 'id', null],
        'industryGroup' => [parent::class, 'industryGroup', null],
        'legalPersonMaximumAvailablePrice' => [parent::class, 'legalPersonMaximumAvailablePrice', null],
        'legalPersonMinimumAvailablePrice' => [parent::class, 'legalPersonMinimumAvailablePrice', null],
        'minimumRequirePrice' => [parent::class, 'minimumRequirePrice', null],
        'numberOfFinanceProvider' => [parent::class, 'numberOfFinanceProvider', null],
        'persianName' => [parent::class, 'persianName', null],
        'persianSymbol' => [parent::class, 'persianSymbol', null],
        'project' => [parent::class, 'project', null],
        'projectEndDate' => [parent::class, 'projectEndDate', null],
        'projectReportingTypeDescription' => [parent::class, 'projectReportingTypeDescription', null],
        'projectStartDate' => [parent::class, 'projectStartDate', null],
        'projectStatusDescription' => [parent::class, 'projectStatusDescription', null],
        'projectStatusId' => [parent::class, 'projectStatusId', null],
        'realPersonMaximumAvailablePrice' => [parent::class, 'realPersonMaximumAvailablePrice', null],
        'realPersonMinimumAvailablePrice' => [parent::class, 'realPersonMinimumAvailablePrice', null],
        'settlementDescription' => [parent::class, 'settlementDescription', null],
        'subIndustryGroup' => [parent::class, 'subIndustryGroup', null],
        'suggestedUnderwritingEndDate' => [parent::class, 'suggestedUnderwritingEndDate', null],
        'suggestedUnderwritingStartDate' => [parent::class, 'suggestedUnderwritingStartDate', null],
        'sumOfFoundingProvided' => [parent::class, 'sumOfFoundingProvided', null],
        'totalAmounts' => [parent::class, 'totalAmounts', null],
        'totalUnit' => [parent::class, 'totalUnit', null],
        'traceCode' => [parent::class, 'traceCode', null],
        'underwritingDuration' => [parent::class, 'underwritingDuration', null],
        'unitPrice' => [parent::class, 'unitPrice', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
