<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transaction extends \App\Entities\Transaction implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'amount' => [parent::class, 'amount', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'deletedAt' => [parent::class, 'deletedAt', null],
        "\0".parent::class."\0".'gateway' => [parent::class, 'gateway', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'invoice' => [parent::class, 'invoice', null],
        "\0".parent::class."\0".'order' => [parent::class, 'order', null],
        "\0".parent::class."\0".'rrn' => [parent::class, 'rrn', null],
        "\0".parent::class."\0".'securePan' => [parent::class, 'securePan', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'terminalId' => [parent::class, 'terminalId', null],
        "\0".parent::class."\0".'token' => [parent::class, 'token', null],
        "\0".parent::class."\0".'traceNumber' => [parent::class, 'traceNumber', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'amount' => [parent::class, 'amount', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'deletedAt' => [parent::class, 'deletedAt', null],
        'gateway' => [parent::class, 'gateway', null],
        'id' => [parent::class, 'id', null],
        'invoice' => [parent::class, 'invoice', null],
        'order' => [parent::class, 'order', null],
        'rrn' => [parent::class, 'rrn', null],
        'securePan' => [parent::class, 'securePan', null],
        'status' => [parent::class, 'status', null],
        'terminalId' => [parent::class, 'terminalId', null],
        'token' => [parent::class, 'token', null],
        'traceNumber' => [parent::class, 'traceNumber', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
